version: '3.9'

services:
  nodejs:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - REDIS_URL=redis://redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=myapp
    depends_on:
      - mongodb
      - redis
      - mysql
    command: 'npm run start:prod'
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
  redis:
    image: redis
    ports:
      - '6379:6379'
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=myapp
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mongodb-data:
  mysql-data:
